name: ctracker
description: Local-only app to track owed change.

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.10
  provider: ^6.0.5
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
